# Generated by Django 5.1.2 on 2025-01-12 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0002_add_common_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="barcode",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="vintage",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1900)]
            ),
        ),
    ]
